### ISSUE TITLE
LeanInfer could not build when tested on Github Codespace

### ISSUE THREAD

**Issue by utensil** [lean-dojo/LeanInfer#3]
The issues were posted [on Zulip](https://leanprover.zulipchat.com/#narrow/stream/219941-Machine-Learning-for-Theorem-Proving/topic/LeanInfer.3A.20Neural.20Network.20Inference.20in.20Lean.204/near/390303744), please check there for more context.

## TL;DR

1. Github Codespace can only compile after `-stdlib=libc++` is removed
2. `lake build` hangs indefinitely in linking, and it's not using much CPU

## Issue Details

I've tried out lean4-example in Github Codespace, I got the following issues:

1. `lake build` fails to compile C++ with Clang++, resolved by removing all `-stdlib=libc++`from the lakefile of LeanInfer

```bash
lean4-example (improve-installation) $ lake build
[23/197] Compiling ffi.cpp
error: > clang++ -c -o ./lake-packages/LeanInfer/build/ffi.o ./lake-packages/LeanInfer/ffi.cpp -fPIC -std=c++11 -stdlib=libc++ -O3 -I /home/codespace/.elan/toolchains/leanprover--lean4---v4.0.0/include
error: stderr:
In file included from ./lake-packages/LeanInfer/ffi.cpp:1:
/home/codespace/.elan/toolchains/leanprover--lean4---v4.0.0/include/lean/lean.h:14:10: fatal error: 'atomic' file not found
#include <atomic>
         ^~~~~~~~
1 error generated.
error: external command `clang++` exited with code 1
```

I ran `bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"` from https://apt.llvm.org/ to fix it, no change.
Then I test the `clang++` command with extra options ` -E -x c++ -v ` at the end, it showed the following search path:

```bash
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /home/codespace/.elan/toolchains/leanprover--lean4---v4.0.0/include
 /usr/local/include
 /usr/lib/llvm-10/lib/clang/10.0.0/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
```

which is shorter than a raw `clang++  -E -x c++ - -v < /dev/null 2>&1` which shows

```bash
ignoring nonexistent directory "/include"
ignoring duplicate directory "/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/x86_64-linux-gnu/c++/9"
#include "..." search starts here:
#include <...> search starts here:
 /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9
 /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/x86_64-linux-gnu/c++/9
 /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/backward
 /usr/local/include
 /usr/lib/llvm-10/lib/clang/10.0.0/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
```

Clearly Clang++ stop looking for the GNU C++ headers if  `-stdlib=libc++` is present. If Github Codespace misses it I guess it would be missed in the environments of many end-users.

2. After resolved issue 1, I end up having the same issue `fatal error: 'onnxruntime_cxx_api.h' file not found`, resolved by 

```
( cd /workspace/ && wget https://github.com/microsoft/onnxruntime/releases/download/v1.15.1/onnxruntime-linux-x64-1.15.1.tgz && tar xzvf  onnxruntime-linux-x64-1.15.1.tgz)
```

Then add `"-I", "/workspaces/onnxruntime-linux-x64-1.15.1/include"` to `flags` in LeanInfer lakefile or just add `CPATH` environment variable as instructed.

3. Run `lake build` after step 2, I have the same linker error `libc++abi: terminating due to uncaught exception of type lean::exception: error loading library, libonnxruntime.so.1.15.1: cannot open shared object file: No such file or directory`, I tried to fix it by adding `"-L", "/workspace/onnxruntime-linux-x64-1.15.1/lib/"` to `moreLinkArgs` then

```
LD_LIBRARY_PATH=/workspaces/onnxruntime-linux-x64-1.15.1/lib/ lake build
```

But the build hangs indefinitely, and it's not using much CPU (<3%). So far, I'm stuck here.

**Comment by utensil** [comment]
Thanks for the solution for issue 1. The cause is actually not "When running lake build, it automatically uses GNU's version and causes the problem.", the cause is that it's trying to use libc++ and found none. My ad hoc solution is just to tell clang++ to use GNU's version and so it compiles. Which could be a potential issue for other users so I consider it an issue to be handled so that end users could have a smooth experience despite environment differences.

As for issue 2, I'm having this for both on Code Space (Ubuntu) and a CentOS server. Can you shed any light on this one? Thanks. It hangs on linking LeanInfer FrontEnd after successfully compiled all other components.

**Comment by yangky11** [comment]
We encountered issue 2 during development. It's likely related to GNU's standard libraries. That was why we only worked with Clang and added the flag `-stdlib=libc++` to prevent it from using GNu's standard libraries. So you probably shouldn't tell clang++ to use GNU's version.

It's not clear to me why GCC cannot compile LeanInfer while Clang can. The compilation process is too tricky for the end-users to get right, and I think the ultimate solution should be cloud build.

**Comment by utensil** [comment]
Thanks, so they could be caused by the same reason!

Unfortunately, it still hangs with Clang++ and libc++:

```
/workspaces/lean4-example (improve-installation) $ CPATH=/workspaces/onnxruntime-linux-x64-1.15.1/include/ LD_LIBRARY_PATH=/workspaces/onnxruntime-linux-x64-1.15.1/lib/:/workspaces/clang+llvm-16.0.0-x86_64-linux-gnu-ubuntu-18.04/lib/x86_64-unknown-linux-gnu/ lake build
[60/197] Linking libleanffi.so
[184/197] Building LeanInfer.Frontend
```

**Comment by yangky11** [comment]
I just added [a script](https://github.com/lean-dojo/LeanInfer/blob/main/scripts/build.sh) for building LeanInfer in GitHub Codespace. The following steps works for me:
1. Launch a codespace on the `main` branch of LeanInfer.
2. Run `source scripts/build.sh`.

Alternatively, you can try [build_example.sh](https://github.com/lean-dojo/LeanInfer/blob/main/scripts/build_example.sh), which builds lean4-example instead of LeanInfer.

**Comment by utensil** [comment]
The scripts work great, the build is successful without hassle.

Then I try to use the built LeanInfer in lean4-example, even after I set

`LD_LIBRARY_PATH` and `LIBRARY_PATH` to `/workspaces/onnxruntime-linux-x64-1.15.1/lib` in Lean 4 Server Env then restart Lean server, Lean InfoView still shows:

```
error loading library, libonnxruntime.so.1.15.1: cannot open shared object file: No such file or directory
```

The only way I succeeded to get around this is to manually run

```
cp /workspaces/onnxruntime-linux-x64-1.15.1/lib/*.so* ~/.elan/toolchains/leanprover--lean4---v4.0.0/lib/
```

And wait a while, then I can successfully use `suggest_tactics`. 🎉

**Comment by utensil** [comment]
Some more debugging:

Given

<img width="814" alt="image" src="https://github.com/lean-dojo/LeanInfer/assets/64258/f31daac9-6e61-4f7d-b861-8480d938a9d6">

For the following Lean code (Lean InfoView output shown in comments):

```lean4
open System

#eval IO.getEnv "LIBRARY_PATH" -- none
#eval IO.getEnv "LD_LIBRARY_PATH"  -- some "./build/lib:./lake-packages/LeanInfer/build/lib:./lake-packages/aesop/build/lib:./lake-packages/std/build/lib:/home/codespace/.elan/toolchains/leanprover--lean4---v4.0.0/lib/lean:/home/codespace/.elan/toolchains/leanprover--lean4---v4.0.0/lib"
#eval IO.getEnv "LEAN_PATH" -- some "./build/lib:./lake-packages/LeanInfer/build/lib:./lake-packages/aesop/build/lib:./lake-packages/std/build/lib:/home/codespace/.elan/toolchains/leanprover--lean4---v4.0.0/lib/lean"
```

It seems that the Server Env are not effective.

**Comment by yangky11** [comment]
@utensil Would you like to try the simplified installation process?
https://github.com/yangky11/lean4-example/tree/LeanInfer-demo

**Comment by samminweng** [comment]
@yangky11 
Thanks for your quick response and hard work! 
I had previously tried out the previous version, but I ran into the issue of the missing libonnxruntime.so.1.15.1 library. However, the new and simplified version fixed the bug and can now correctly display the list of suggested tactics in my VS code. 

![image](https://github.com/lean-dojo/LeanInfer/assets/5901362/9834321b-dc99-45ba-9d19-7cc330cc827b)

**Comment by yangky11** [comment]
@samminweng Thanks! May I know what platform you're using (Linux, Intel macOS, M1/M2 macOS)?

**Comment by samminweng** [comment]
The platform is Ubuntu 20.04 (which was installed on Windows for Linux), and CPU is Intel i5 CPU. Thanks.

**Comment by yangky11** [comment]
That's great to hear! So it may even work for WSL. We didn't test it though..

**Comment by utensil** [comment]
> @utensil Would you like to try the simplified installation process? https://github.com/yangky11/lean4-example/tree/LeanInfer-demo

I've just tested on Codespace and it works smoothly. All I ever need is only the line:

```
git lfs install && git clone https://huggingface.co/kaiyuy/onnx-leandojo-lean4-tacgen-byt5-small
```

for downloading the model, the rest is handled by VSCode Lean 4 extension.

There are some observations:

1. `lake update` doesn't seem to required. It works without it and on Zulip this is usually disencouraged due to it might update some other dependencies (like Mathlib4) accidentally then make a mess.

2. There's still a building process and it takes a while. Mostly it builds Std, and it also builds and links LeanInfer, as shown below:

<img width="1134" src="https://github.com/lean-dojo/LeanInfer/assets/64258/1c839cfa-6f01-4cc3-9cc8-11291cb13bd7">

<img width="1134" src="https://github.com/lean-dojo/LeanInfer/assets/64258/5e22f7b2-9e02-4477-865b-52536a39cf73">

Finally, celebration!

<img width="1134"  src="https://github.com/lean-dojo/LeanInfer/assets/64258/c4314ff9-6eea-49d4-b5a2-f091db080a06">

**Comment by yangky11** [comment]
Thanks!  The building process is expected, and I'll remove `lake update`.
